# name: Build, push and deploy backend, API (main)

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   docker:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check PR source branch
#         run: |
#           if [ "${{ github.head_ref }}" != "dev" ]; then
#             echo "PR must come from dev branch!"
#             exit 1
#           fi

#       - name: Check out repository
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image (prod)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:latest ./backend

#       - name: Push Docker image (prod)
#         run: |
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:latest

#       - name: Deploy to Render (prod)
#         env:
#           deploy_url: ${{ secrets.RENDER_DEPLOY_URL }}
#         run: |
#           curl "$deploy_url"

# name: Build, Push and Deploy Backend (main)

# # Trigger endast på push till main (efter PR och merge)
# on:
#   push:
#     branches:
#       - main

# jobs:
#   docker:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout kod
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # Logga in på Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # Bygg Docker image
#       - name: Build Docker image (prod)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:latest ./backend

#       # Pusha Docker image
#       - name: Push Docker image (prod)
#         run: |
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:latest

#       # Deploy till Render
#       - name: Deploy to Render (prod)
#         env:
#           deploy_url: ${{ secrets.RENDER_DEPLOY_URL }}
#         run: |
#           curl "$deploy_url"
