name: Build, push and deploy backend, API (main)

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

      
    - name: Build Docker image (prod)
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:latest ./backend

      
    - name: Push Docker image (prod)
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:latest

      
    - name: Deploy to Render (prod)
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_URL }}
      # run: |
      #   curl "$deploy_url"

        run: |
          curl -X POST "$deploy_url" -H "Accept: application/json" --fail