name: PR Build Backend

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "PR must come from dev branch!"
            exit 1
          fi

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meetups-server:pr ./backend
