name: PR Build Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-frontend-main:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "PR must come from dev branch!"
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0

      - name: Install dependencies
        working-directory: ./frontend
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        run: npm run build
